namespace: external-secrets

images:
  - name: ghcr.io/external-secrets/external-secrets
    newName: ghcr.io/external-secrets/external-secrets
    newTag: v0.1.3

resources:
  - ./ClusterRole
  - ./ClusterRoleBinding
  - ./Deployment
  - ./Role
  - ./RoleBinding
  - ./ServiceAccount
